version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 259687664332.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg RDS_HOST=$RDS_HOST --build-arg RDS_DATABASE=$RDS_DATABASE --build-arg RDS_PASSWORD=$RDS_PASSWORD --build-arg RDS_USERNAME=$RDS_USERNAME -t blacklist .
      - docker tag blacklist:latest 259687664332.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 259687664332.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"container-blacklist-ver02","imageUri":"blacklist:latest 259687664332.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"blacklist:latest 259687664332.dkr.ecr.us-east-1.amazonaws.com/blacklist:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json